SETTINGS_MAP = {
    "SECRET_KEY": "secret_key",
    "DEBUG": "debug",
    "ALLOWED_HOSTS": "allowed_hosts",
    "INSTALLED_APPS": "installed_apps",
    "MIDDLEWARE": "middleware",
    "ROOT_URLCONF": "root_urlconf",
    "WSGI_APPLICATION": "wsgi_application",
    "DATABASES": "databases",
    "AUTH_PASSWORD_VALIDATORS": "auth_password_validators",
    "LANGUAGE_CODE": "language_code",
    "TIME_ZONE": "time_zone",
    "USE_I18N": "use_i18n",
    "USE_TZ": "use_tz",
    "DEFAULT_AUTO_FIELD": "default_auto_field",
    "LOGGING_CONFIG": "logging_config",
    "LOGGING": "logging",
}

DJANGO_SETTINGS_KEYS = {
    "SECRET_KEY",
    "DEBUG",
    "ALLOWED_HOSTS",
    "INSTALLED_APPS",
    "MIDDLEWARE",
    "ROOT_URLCONF",
    "WSGI_APPLICATION",
    "DATABASES",
    "AUTH_PASSWORD_VALIDATORS",
    "LANGUAGE_CODE",
    "TIME_ZONE",
    "USE_I18N",
    "USE_TZ",
    "DEFAULT_AUTO_FIELD",
    "LOGGING_CONFIG",
    "LOGGING",
}
